package kb.dev.trackme

enum class SessionState {
    ACTIVE,
    PAUSE,
    COMPLETE
}

const val EXTRA_CMD_REQUEST_TYPE = "EXTRA_CMD_REQUEST_TYPE"
const val EXTRA_CMD_REQUEST_PAUSE_SESSION = "EXTRA_REQUEST_PAUSE_SESSION"
const val EXTRA_CMD_REQUEST_RESUME_SESSION = "EXTRA_REQUEST_RESUME_SESSION"
const val EXTRA_CMD_REQUEST_START_SESSION = "EXTRA_REQUEST_START_SESSION"
const val EXTRA_CMD_REQUEST_COMPLETE_SESSION = "EXTRA_REQUEST_COMPLETE_SESSION"

const val PREF_KEY_SESSION_STATE = "PREF_KEY_SESSION_STATE"
const val PREF_KEY_PERMISSION_GRANT_STATUS = "PREF_KEY_PERMISSION_GRANT_STATUS"
const val PREF_KEY_PERMISSION_SESSION_BACKUP = "PREF_KEY_PERMISSION_SESSION_BACKUP"